--creating basic sequence

CREATE SEQUENCE DEPT_S;

SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='DEPT_S';

-- select length('9999999999999999999999999999') from dual;

DROP TABLE DEPT_TEST_S;

CREATE TABLE DEPT_TEST_S
( DEPNO NUMBER PRIMARY KEY,
  DNAME VARCHAR2(100)
 );
  
INSERT INTO DEPT_TEST_S (DEPNO, DNAME) 
VALUES (DEPT_S.NEXTVAL,'Sales');

INSERT INTO DEPT_TEST_S (DEPNO, DNAME) 
VALUES (DEPT_S.NEXTVAL,'Operation');

SELECT * FROM DEPT_TEST_S;

SELECT DEPT_S.CURRVAL FROM DUAL;

SELECT DEPT_S.nextval FROM DUAL;

INSERT INTO DEPT_TEST_S (DEPNO, DNAME) 
VALUES (DEPT_S.NEXTVAL,'IT');

SELECT * FROM DEPT_TEST_S;
--------------------------------------------------------------------------
DROP SEQUENCE DEPT_S1;

CREATE SEQUENCE DEPT_S1
START WITH 10
INCREMENT BY 20;

SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='DEPT_S1';

DELETE FROM DEPT_TEST_S;

INSERT INTO DEPT_TEST_S (DEPNO, DNAME) 
VALUES (DEPT_S1.NEXTVAL,'Marketing');

INSERT INTO DEPT_TEST_S (DEPNO, DNAME) 
VALUES (DEPT_S1.NEXTVAL,'Help Desk');

SELECT * FROM DEPT_TEST_S;
---------------------------------------------------------------------------

DELETE FROM DEPT_TEST_S;

DROP SEQUENCE DEPT_S2;

CREATE SEQUENCE DEPT_S2
INCREMENT BY -5;

SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='DEPT_S2';

INSERT INTO DEPT_TEST_S (DEPNO, DNAME) 
VALUES (DEPT_S2.NEXTVAL,'Marketing');

INSERT INTO DEPT_TEST_S (DEPNO, DNAME) 
VALUES (DEPT_S2.NEXTVAL,'Help Desk');

SELECT * FROM DEPT_TEST_S;
----------------------------------------

UPDATE DEPT_TEST_S
SET DEPNO=DEPT_S2.NEXTVAL;

SELECT * FROM DEPT_TEST_S
ORDER BY 1;
----------------------------------------------

--you can create default value as sequence in create table

DROP SEQUENCE EMP_S;

CREATE SEQUENCE EMP_S;

DROP TABLE EM;

CREATE TABLE EM
( EMPID NUMBER DEFAULT EMP_S.NEXTVAL PRIMARY KEY ,
  NAME VARCHAR2(100),
  DEPTNO NUMBER
);

  
INSERT INTO EM (NAME )  VALUES ('JAMES');

INSERT INTO EM (NAME )  VALUES ('Mark');

SELECT * FROM EM;
------------------------------------------------------------

delete from DEPT_TEST_S;
delete FROM EM;
drop sequence DEPT_S;
CREATE SEQUENCE DEPT_S;
--using currval and nextval  in inserting scripts 
--insert department called (support ) in table DEPT_TEST_S using the squence  DEPT_S
--then insert 3 employees to EM table that work in support department

INSERT INTO DEPT_TEST_S (DEPNO, DNAME) 
VALUES (DEPT_S.NEXTVAL,'support');
INSERT INTO EM (NAME,DEPTNO )  VALUES ('ali',DEPT_S.CURRVAL);
INSERT INTO EM (NAME,DEPTNO )  VALUES ('ahmed',DEPT_S.currval);
INSERT INTO EM (NAME,DEPTNO )  VALUES ('samer',DEPT_S.currval);

SELECT * FROM DEPT_TEST_S;

SELECT * FROM EM;
---------------------------------------------------------------

--you can alter the sequence

SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='DEPT_S';

ALTER SEQUENCE DEPT_S
INCREMENT BY 100;

SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='DEPT_S';

ALTER SEQUENCE DEPT_S
CACHE 30;

SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='DEPT_S';

ALTER SEQUENCE DEPT_S
maxvalue 9999;

SELECT * FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='DEPT_S';

--you can not change the start with
ALTER SEQUENCE DEPT_S 
START WITH 170;
----------------------------------------

DROP SEQUENCE S_CYCLE;


CREATE SEQUENCE S_CYCLE
START WITH 1
INCREMENT BY 1
MAXVALUE 5
nocache 
CYCLE;

SELECT S_CYCLE.NEXTVAL FROM DUAL;
SELECT S_CYCLE.NEXTVAL FROM DUAL;
SELECT S_CYCLE.NEXTVAL FROM DUAL;
SELECT S_CYCLE.NEXTVAL FROM DUAL;
SELECT S_CYCLE.NEXTVAL FROM DUAL;

SELECT S_CYCLE.NEXTVAL FROM DUAL;









  















