--all the dictionary  views stored in dictionary

SELECT * FROM DICTIONARY
ORDER BY 1;


SELECT * FROM DICTIONARY
WHERE TABLE_NAME LIKE '%COL%';

----------------------------------------------

--USER_OBJECTS/ALL_OBJECTS

DESC USER_OBJECTS;

SELECT OBJECT_NAME,OBJECT_ID,OBJECT_TYPE,CREATED,LAST_DDL_TIME,STATUS, GENERATED
FROM USER_OBJECTS;

SELECT OBJECT_NAME,OBJECT_ID,OBJECT_TYPE,CREATED,LAST_DDL_TIME,STATUS, GENERATED
FROM USER_OBJECTS
WHERE OBJECT_NAME='EMPLOYEES';

SELECT OWNER,OBJECT_NAME,OBJECT_ID,OBJECT_TYPE,CREATED,LAST_DDL_TIME,STATUS, GENERATED
FROM ALL_OBJECTS
WHERE OBJECT_NAME='EMPLOYEES';


--USER_CATALOG IS DICTIONARY Contains only table_name, table_type
--only table,view, index,synonym
SELECT * FROM USER_CATALOG


--cat is a synonym for USER_CATALOG
SELECT * FROM CAT;
------------------------------------------------

--USER_TABLES/ all_tables

SELECT *
FROM USER_TABLES;

SELECT OWNER,TABLE_NAME 
FROM ALL_TABLES;

--tabS is synonym for user_tables
SELECT TABLE_NAME FROM TABS;

------------------------------------
--USER_TAB_COLUMNS
SELECT * FROM
USER_TAB_COLUMNS
WHERE TABLE_NAME  ='EMPLOYEES'
ORDER BY TABLE_NAME,COLUMN_ID
-----------------------------------------------





--USER_CONSTRAINTS

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME='EMPLOYEES'; ---DEPT_ID_PK

SELECT * FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME='DEPT_ID_PK';

--old syntax--
SELECT M.OWNER,M.TABLE_NAME,M.CONSTRAINT_NAME,M.CONSTRAINT_TYPE,M.R_CONSTRAINT_NAME,D.TABLE_NAME
FROM USER_CONSTRAINTS M,
USER_CONSTRAINTS D
WHERE M.R_CONSTRAINT_NAME=D.CONSTRAINT_NAME(+)
AND M.TABLE_NAME='EMPLOYEES'

--new syntax--
SELECT M.OWNER,M.TABLE_NAME,M.CONSTRAINT_NAME,M.CONSTRAINT_TYPE,M.R_CONSTRAINT_NAME,D.TABLE_NAME
FROM USER_CONSTRAINTS M LEFT OUTER JOIN
USER_CONSTRAINTS D
ON ( M.R_CONSTRAINT_NAME=D.CONSTRAINT_NAME)
WHERE M.TABLE_NAME='EMPLOYEES'

--USER_CONS_COLUMNS
SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME='EMPLOYEES'; ---EMP_EMP_ID_PK

SELECT * FROM USER_CONS_COLUMNS
WHERE TABLE_NAME='EMPLOYEES'

SELECT * FROM USER_CONS_COLUMNS
WHERE TABLE_NAME='XX_EMP_COL_CONST1'


SELECT M.OWNER,M.TABLE_NAME,M.CONSTRAINT_NAME, M.CONSTRAINT_TYPE
FROM USER_CONSTRAINTS M
WHERE TABLE_NAME='EMPLOYEES';

SELECT M.OWNER,M.TABLE_NAME,M.CONSTRAINT_NAME,M.CONSTRAINT_TYPE,D.COLUMN_NAME, D.POSITION
FROM USER_CONSTRAINTS M,
USER_CONS_COLUMNS D
WHERE M.CONSTRAINT_NAME=D.CONSTRAINT_NAME
AND M.TABLE_NAME='EMPLOYEES';

SELECT M.OWNER,M.TABLE_NAME,M.CONSTRAINT_NAME,M.CONSTRAINT_TYPE,D.COLUMN_NAME, D.POSITION
FROM USER_CONSTRAINTS M JOIN
USER_CONS_COLUMNS D
ON( M.CONSTRAINT_NAME=D.CONSTRAINT_NAME)
WHERE M.TABLE_NAME='EMPLOYEES';

--TO PICK ALL THE CONSTRAINT IN ONE QUERY
SELECT COUNT(1) FROM USER_CONS_COLUMNS;

SELECT M.OWNER,M.TABLE_NAME,M.CONSTRAINT_NAME,R_M.COLUMN_NAME,
M.CONSTRAINT_TYPE,M.SEARCH_CONDITION,M.STATUS,D.CONSTRAINT_NAME,D.TABLE_NAME,
R_D.COLUMN_NAME,R_D.POSITION
FROM USER_CONSTRAINTS M,
USER_CONSTRAINTS D,
USER_CONS_COLUMNS R_M,
USER_CONS_COLUMNS R_D
WHERE M.R_CONSTRAINT_NAME=D.CONSTRAINT_NAME(+)
AND M.CONSTRAINT_NAME=R_M.CONSTRAINT_NAME
AND D.CONSTRAINT_NAME=R_D.CONSTRAINT_NAME(+)
--AND M.TABLE_NAME='EMPLOYEES'
ORDER BY M.OWNER,M.TABLE_NAME,R_D.POSITION 
-----------------------------------------------------------------------------------------------------------

--ADDING COMMENTS ON TABLE/ COLUMN

COMMENT ON TABLE  EMPLOYEES
IS 'this table contains employees data';

SELECT * FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='EMPLOYEES';

-----------
COMMENT ON COLUMN  EMPLOYEES.SALARY
IS 'THE SALARY OF EMPLOYEE :)';

SELECT * FROM USER_COL_COMMENTS
WHERE TABLE_NAME='EMPLOYEES'
AND COLUMN_NAME='SALARY';


------------------------------



















